// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// has_mc_cpp
LogicalVector has_mc_cpp(List list, NumericVector values);
RcppExport SEXP _rdp2_has_mc_cpp(SEXP listSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type list(listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(has_mc_cpp(list, values));
    return rcpp_result_gen;
END_RCPP
}
// mrcheck_cpp
NumericVector mrcheck_cpp(NumericVector xs);
RcppExport SEXP _rdp2_mrcheck_cpp(SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(mrcheck_cpp(xs));
    return rcpp_result_gen;
END_RCPP
}
// add_to_mrset_cpp
NumericVector add_to_mrset_cpp(NumericVector vec, double value);
RcppExport SEXP _rdp2_add_to_mrset_cpp(SEXP vecSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(add_to_mrset_cpp(vec, value));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rdp2_has_mc_cpp", (DL_FUNC) &_rdp2_has_mc_cpp, 2},
    {"_rdp2_mrcheck_cpp", (DL_FUNC) &_rdp2_mrcheck_cpp, 1},
    {"_rdp2_add_to_mrset_cpp", (DL_FUNC) &_rdp2_add_to_mrset_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rdp2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
