# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

has_list_multiple_cpp <- function(list, values) {
    .Call(`_rdp2_has_list_multiple_cpp`, list, values)
}

has_list_single_cpp <- function(xs, y) {
    .Call(`_rdp2_has_list_single_cpp`, xs, y)
}

