# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

has_mc_cpp <- function(list, values) {
    .Call(`_rdp2_has_mc_cpp`, list, values)
}

